# Site
repository: lucianpalaghe/resume
favicon: images/favicon.ico

version: 2

name: Lucian Palaghe
title: Java Technical Lead@Accesa
email: l.palaghe@gmail.com
phone: "+40733041242"

# Dark Mode (true/false/never)
darkmode: false

github_username:  lucianpalaghe
linkedin_username: lucianpalaghe
# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Software developer with experience working in a variety of technical environments. Passionate about automation, whether it's continuous integration, deployment or the operational side of software development. Skilled in Software Development, Java and its vast ecosystem including the Spring framework, as well as other programming languages, with an emphasis on clean code practices. Not a stranger to GitHub Actions, Kubernetes or Helm either. Strong engineering professional who is looking for interesting problems to solve, wise people to learn from and enthusiasts to guide and share knowledge with. Eager to learn new things and open for new challenges.

content:

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Java Technical Lead
        sub_title: "@Accesa"
        quote: Projects in the banking industry
        caption: June 2022 - Present
        description: |
              * involved in developing a customer facing application used to express approval or disproval. Involved in developing an in-bank property evaluation application. Both built using API driven development and a microservice architecture, Spring Boot, Hibernate, Oracle Database persistence, Jenkins CI/CD, deployed in OpenShift.
              * refactored an existing batch job running application built with Spring Boot, Batch, Hibernate, Oracle Database persistence
              * involved in mentoring juniors
              * involved in technical interviews
              * involved in internal Accesa projects
      - layout: left
        title: DevOps engineer
        sub_title: "@PSS"
        quote: Retail software solution - Spring Boot based microservices(Java 11) deployed in containers, MongoDB persistence, Keycloak authentication, Maven and NPM build management, GitHub
        caption: 2021 - June 2022
        description: |
              * created the CI/CD strategy, implemented it with GitHub Actions
              * created deployments with Helm and Kubernetes(managed, AKS) for various environments
              * implemented GitOps with Argo CD
              * implemented automatic versioning and automated dependency updates
              * implemented cloud monitoring with Prometheus, Grafana, Loki, load testing with K6
              * code reviews for changes to the Java code-base, pair programming, Java programming on occasion
      - layout: left
        title: Full stack developer
        sub_title: "@PSS"
        quote: Retail software solution - Spring Boot based microservices(Java 8) deployed in containers, MongoDB persistence, OpenAPI, VueJS+Vuetify front-end, Maven and NPM build management, Jenkins, GitLab
        caption: 2019 - 2021
        description: |
              * definied new APIs, service implementation in Java, wrote unit and integration tests with JUnit 4
              * created VueJS front-end components
              * wrote functional tests with Selenium and Cucumber
              * wrote new Jenkins pipelines that facilitated running all the tests, CI and artifact deployment to Sonatype Nexus
              * code reviews and GitLab merge requests
              * wrote markdown documentation and UML diagrams(PlantUML)
              * helped various team members overcome technical challenges
      - layout: left
        title: Java developer
        sub_title: "@PSS"
        quote: Self-checkout software solution - Monolith application based on an in-house developed Java framework, relational database persistence(SQLite), Swing front-end
        caption: 2017 - 2019
        description: |
            * implemented changes in the Swing GUI
            * technical analysis for customer requirements
            * developed integrations with external payment systems
      - layout: left
        title: Java developer
        sub_title: "@PSS"
        quote: Employee holiday tracking app, Spring Boot, Hibernate, Vaadin, OAuth sign-on with Microsoft Azure and Jira, employee information integrations with Jira and Tempo
        caption: 2019
        description: |
            POC application for streamlining holiday request approval and management.
      - layout: left
        title: Android developer
        sub_title: "@PSS"
        quote: Android application that provided store customers with product information. The information was provided by an external REST service using the product barcode as an identifier
        caption: 2017
        description: |
            Developed the application from scratch.
      - layout: left
        title: Python web developer
        sub_title: "@PSS"
        quote: Python and Django web based marketplace application prototype
        caption: 2016
        description: |
            Developed prototype from start to finish, ended up supporting product catalog search, fully functioning cart with basic discounts and transaction export to JSON
      - layout: left
        title: Java developer
        sub_title: "@PSS"
        quote: Payment software solution - monolith application that supported a secure dataflow for credit/debit card data from the pin-entry-device to the acquiring bank that processed the payments
        caption: 2015
        description: |
            Took over parts of the code-base, adapted the dataflow(payment, settlement, reversal) to various changing specifications(EMV, APACS, etc.).
      - layout: left
        title: Java developer
        sub_title: "@PSS"
        quote: Retail software solution - monolith application based on an in-house developed Java framework, relational database persistence(Oracle, MSSQL Server), swing front-end, Python scripts for various kinds of automation
        caption: 2013 - 2015
        description: |
            * implemented complete data flows for store operators(screen to database and back)
            * integrated with external components through REST and SOAP web services
            * created REST web sevices and exposing them to exernal consumers
            * various kinds of data export to csv, XML and PDF
            * various SQL related tasks(defining database table structures, triggers, stored procedures)
            * business and techincal analysis for customer requirements
            * created Word based documentation
      - layout: left
        title: Working with people
        sub_title: "@PSS"
        caption: since 2015
        description: |
            Involved in doing technical interviews for junior Java developers, helped with their on-boarding, evaluated their progress and potential, mentored them along their way.
      - layout: left
        title: Java instructor
        sub_title: "@Scoala Informala"
        caption: 2020 - 2021
        description: |
          Taught Java for beginners as part of a 5-month course(participated in 3 consecutive courses).

  - title: Certifications
    layout: list
    content:
      - layout: top-middle
        title: GCP Professional Cloud Architect
        link: https://www.credential.net/5cabeff2-35b8-4f97-8154-21b770939d70
        quote: >
          February 2023
        description: |
          A Google Cloud Certified - Professional Cloud Architect enables organizations to leverage Google Cloud technologies. Through an understanding of cloud architecture and Google technology, this individual can design, develop, and manage robust, secure, scalable, highly available, and dynamic solutions to drive business objectives.
          A Google Cloud Certified - Professional Cloud Architect has demonstrated in our assessment their ability to:
          * Design and plan a cloud solution architecture
          * Manage and provision the cloud solution infrastructure
          * Design for security and compliance
          * Analyze and optimize technical and business processes
          * Manage implementations of cloud architecture
          * Ensure solution and operations reliability

      - layout: top-middle
        title: GCP Professional Cloud Security Engineer
        link: https://www.credential.net/4d63f9d7-3bbf-4937-bc05-08633f184737
        quote: >
          April 2023
        description: |
          A Cloud Security Engineer enables organizations to design and implement secure workloads and infrastructure on Google Cloud. Through an understanding of security best practices and industry security requirements, this individual designs, develops, and manages a secure infrastructure by leveraging Google security technologies. The Cloud Security Engineer should be proficient in all aspects of cloud Security including identity and access management, defining organizational structure and policies, using Google technologies to provide data protection, configuring network security defenses, collecting and analyzing Google Cloud logs, managing incident responses, and demonstrating an understanding of the application of dynamic regulatory considerations.
          The Professional Cloud Security Engineer exam assesses your ability to:
          * Configure access within a cloud solution environment
          * Configure network security
          * Ensure data protection
          * Manage operations within a cloud solution environment
          * Ensure compliance

      - layout: top-middle
        title: GCP Professional Cloud Database Engineer
        link: https://www.credential.net/10ddae1c-6e11-4aee-8cc2-44f3bcc24447
        quote: >
          May 2023
        description: |
          A Professional Cloud Database Engineer is a database professional with two years of Google Cloud experience and five years of overall database and IT experience. The Professional Cloud Database Engineer designs, creates, manages, and troubleshoots Google Cloud databases used by applications to store and retrieve data. The Professional Cloud Database Engineer should be comfortable translating business and technical requirements into scalable and cost-effective database solutions.
          The Professional Cloud Database Engineer exam assesses your ability to:
          * Design scalable and highly available cloud database solutions
          * Manage a solution that can span multiple database solutions
          * Migrate data solutions
          * Deploy scalable and highly available databases in Google Cloud

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Chameleon
        link: https://github.com/lucianpalaghe/chameleon
        quote: >
          Game score-keeping app
        description: |
          SPA made with Svelte, TailwindCSS, Firestore and Firebase Hosting.
      - layout: top-middle
        title: Ambient Box
        link: https://github.com/lucianpalaghe/ambient-box
        quote: >
          ESP32 and BME680 sensor
        description: |
          ESP32 based mobile temperature, humidity, pressure, altitude(calculated) and IAQ sensor. Made form a TTGO T-Display board, BME680 sensor, 3.7V LiPo battery and 3D printed case.
      - layout: top-middle
        title: Ambient Box PWA
        link: https://github.com/lucianpalaghe/ambient-box-pwa
        quote: >
          Companion app for Ambient Box
        description: |
          Companion PWA for https://github.com/lucianpalaghe/ambient-box written with Vue and Typscript. Connects to the Ambint Box through BLE and displays sensor data.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Universitatea Transilvania din Bra»ôov
        caption: 2010 - 2013
        sub_title: BSc Informatica aplicata

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
